create table country
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    continent varchar(255) not null
);

create table host
(
    id         bigint generated by default as identity
        primary key,
    name       varchar(255) not null,
    surname    varchar(255) not null,
    country_id bigint       references country on delete set null
);

create table category
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    description varchar(4000)
);

create table smestuvanje
(
    id        bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    category  varchar(255),
    host_id   bigint references host,
    num_rooms integer,
    iznajmeno boolean default false
);

create table app_user
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    role                       varchar(50),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true
);

create table reservation
(
    id             bigint generated by default as identity
        primary key,
    name           varchar(255),
    oddatum        date    not null,
    dodatum        date    not null,
    smesteni       integer not null,
    smestuvanje_id bigint references smestuvanje,
    user_username  varchar(255) references app_user (username),
    confirmed      boolean default false
);

create table app_user_temp_reservation
(
    app_user_username   varchar(255) references app_user (username),
    temp_reservation_id bigint references smestuvanje,

    primary key (app_user_username, temp_reservation_id)
);

create index idx_user_username on app_user (username);
create index idx_user_role on app_user (role);
create index idx_smestuvanje_host on smestuvanje (host_id);
create index idx_reservation_user on reservation (user_username);
