create table if not exists public.country
(
    id        bigint generated by default as identity
    primary key,
    continent varchar(255),
    name      varchar(255)
    );

alter table public.country
    owner to emt;

create table if not exists public.host
(
    id         bigint generated by default as identity
    primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint
    constraint "FK2g83copq8rn9b4pkqlkc2vnbo"
    references public.country
    );

alter table public.host
    owner to emt;

create table if not exists public.smestuvanje
(
    id        bigint generated by default as identity
    primary key,
    category  varchar(255)
    constraint smestuvanje_category_check
    check ((category)::text = ANY
((ARRAY ['ROOM'::character varying, 'HOUSE'::character varying, 'FLAT'::character varying, 'APARTMENT'::character varying, 'HOTEL'::character varying, 'MOTEL'::character varying])::text[])),
    iznajmeno boolean not null,
    name      varchar(255),
    num_rooms integer,
    host_id   bigint
    constraint "FKr104j7i6dguovrw4qaesovxcb"
    references public.host
    );

alter table public.smestuvanje
    owner to emt;

create table if not exists public.app_user
(
    username varchar(255) not null
    primary key,
    name     varchar(255),
    password varchar(255),
    role     varchar(255)
    constraint app_user_role_check
    check ((role)::text = ANY
((ARRAY ['ROLE_USER'::character varying, 'ROLE_HOST'::character varying])::text[])),
    surname  varchar(255)
    );

alter table public.app_user
    owner to emt;

create table if not exists public.reservation
(
    id             bigint generated by default as identity
    primary key,
    confirmed      boolean not null,
    dodatum        date,
    name           varchar(255),
    oddatum        date,
    smesteni       integer not null,
    smestuvanje_id bigint
    constraint "FKb5vo08mf92ciwpsan2adc16df"
    references public.smestuvanje,
    user_username  varchar(255)
    constraint "FKc290a8g8xsfv3vg2cjxn8o52k"
    references public.app_user
    );

alter table public.reservation
    owner to emt;

create table if not exists public.app_user_temp_reservation
(
    user_username       varchar(255) not null
    constraint "FKoh6xux1dxo67i86lxvd8py7a6"
    references public.app_user,
    temp_reservation_id bigint       not null
    constraint "UKpwbnw97y12h1rlvfc1gq4g4cx"
    unique
    constraint "FK1nk73xaq67smxh3qcyioktefv"
    references public.smestuvanje
    );

alter table public.app_user_temp_reservation
    owner to emt;


create index idx_user_username on app_user (username);
create index idx_user_role on app_user (role);
create index idx_smestuvanje_host on smestuvanje (host_id);
create index idx_reservation_user on reservation (user_username);
